# Generated by Django 5.1.7 on 2025-04-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_stage_dietplan_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
