# Generated by Django 5.1.7 on 2025-05-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10)),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('unit_count', models.PositiveIntegerField()),
                ('item_form', models.CharField(choices=[('capsule', 'Capsule'), ('tablet', 'Tablet'), ('syrup', 'Syrup'), ('injection', 'Injection')], max_length=20)),
                ('used_for', models.TextField()),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('other', 'Other')], max_length=20)),
                ('prescription_required', models.BooleanField(default=True)),
                ('shelf_life', models.CharField(max_length=20)),
                ('food_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('not_specified', 'Not specified')], default='not_specified', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
            ],
        ),
    ]
