# Generated by Django 5.1.7 on 2025-05-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='food_preference',
            field=models.CharField(choices=[('Veg', 'Vegetarian'), ('Non_veg', 'Non-Vegetarian'), ('Not_specified', 'Not specified')], default='not_specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='item_form',
            field=models.CharField(choices=[('Capsule', 'Capsule'), ('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection')], max_length=20),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
